server:
  address: localhost
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=StudentManager;encrypt=true;trustServerCertificate=true;
    username: student_manager
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
