server:
  address: localhost
  port: 8080

spring:
  # mvc:
  #   format:
  #     date-time: dd/MM/yy HH:mm
  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB
      # location: c:/Users/manhn/upload
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=StudentManager;encrypt=true;trustServerCertificate=true;
    username: student_manager
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
